CREATE TABLE IF NOT EXISTS measurements (
  id bigserial NOT NULL,
  mtime timestamp with time zone,
  ecolab_id text,
  p1_ppm real,
  p2_ppm real,
  p3_ppm real,
  p4_ppm real,
  p5_ppm real,
  p6_ppm real,
  p7_ppm real,
  p8_ppm real,
  p9_ppm real,
  p1_mgm3 real,
  p2_mgm3 real,
  p3_mgm3 real,
  p4_mgm3 real,
  p5_mgm3 real,
  p6_mgm3 real,
  p7_mgm3 real,
  p8_mgm3 real,
  p9_mgm3 real,
  sid1 text,
  sid2 text,
  sid3 text,
  sid4 text,
  sid5 text,
  sid6 text,
  sid7 text,
  sid8 text,
  sid9 text,
  temp real,
  hum real,
  PRIMARY KEY (id)
);